//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36323
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace More.VisualStudio.Editors
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0" )]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
        internal SR()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ( object.ReferenceEquals( resourceMan, null ) )
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager( "More.VisualStudio.Editors.SR", typeof( SR ).Assembly );
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified custom tool does not support &quot;*{0}&quot; files..
        /// </summary>
        internal static string CodeGeneratorFileTypeNotSupported
        {
            get
            {
                return ResourceManager.GetString( "CodeGeneratorFileTypeNotSupported", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {0} No classes implementing System.Data.Entity.DbContext were found..
        /// </summary>
        internal static string DbContextClassNotFound
        {
            get
            {
                return ResourceManager.GetString( "DbContextClassNotFound", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred during code generation: &quot;{0}&quot;.
        /// </summary>
        internal static string GenerateError
        {
            get
            {
                return ResourceManager.GetString( "GenerateError", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No supported interfaces were found to implement. Code generation is supported for {0}, {1}, and {2}..
        /// </summary>
        internal static string NoInterfacesFound
        {
            get
            {
                return ResourceManager.GetString( "NoInterfacesFound", resourceCulture );
            }
        }
    }
}
