//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace More
{
    using global::System;
    using global::System.Reflection;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0" )]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessage
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
        internal ExceptionMessage()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ( object.ReferenceEquals( resourceMan, null ) )
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager( "More.ExceptionMessage", typeof( ExceptionMessage ).GetTypeInfo().Assembly );
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Year, Month, and Day parameters describe an un-representable DateTime..
        /// </summary>
        internal static string ArgumentOutOfRangeBadYearMonthDay
        {
            get
            {
                return ResourceManager.GetString( "ArgumentOutOfRangeBadYearMonthDay", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Era value was not valid..
        /// </summary>
        internal static string ArgumentOutOfRangeInvalidEraValue
        {
            get
            {
                return ResourceManager.GetString( "ArgumentOutOfRangeInvalidEraValue", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Month must be between one and twelve..
        /// </summary>
        internal static string ArgumentOutOfRangeMonth
        {
            get
            {
                return ResourceManager.GetString( "ArgumentOutOfRangeMonth", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Non-negative number required..
        /// </summary>
        internal static string ArgumentOutOfRangeNeedNonNegNum
        {
            get
            {
                return ResourceManager.GetString( "ArgumentOutOfRangeNeedNonNegNum", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valid values are between {0} and {1}, inclusive..
        /// </summary>
        internal static string ArgumentOutOfRangeRange
        {
            get
            {
                return ResourceManager.GetString( "ArgumentOutOfRangeRange", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The result is out of the supported range for this calendar. The result should be between {0} (Gregorian date) and {1} (Gregorian date), inclusive..
        /// </summary>
        internal static string ArgumentResultCalendarRange
        {
            get
            {
                return ResourceManager.GetString( "ArgumentResultCalendarRange", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A required service of type &apos;{0}&apos; with a key of &apos;{1}&apos; could not be found..
        /// </summary>
        internal static string MissingRequiredKeyedService
        {
            get
            {
                return ResourceManager.GetString( "MissingRequiredKeyedService", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified file of type &apos;{0}&apos; must implement &apos;{1}&apos; in order to be converted to a platform-specified file..
        /// </summary>
        internal static string NativeFileNotSupported
        {
            get
            {
                return ResourceManager.GetString( "NativeFileNotSupported", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified folder of type &apos;{0}&apos; must implement &apos;{1}&apos; in order to be converted to a platform-specified folder..
        /// </summary>
        internal static string NativeFolderNotSupported
        {
            get
            {
                return ResourceManager.GetString( "NativeFolderNotSupported", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A storage item of type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string NativeStorageItemNotSupported
        {
            get
            {
                return ResourceManager.GetString( "NativeStorageItemNotSupported", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The path &apos;{0}&apos; was not found..
        /// </summary>
        internal static string PathNotFound
        {
            get
            {
                return ResourceManager.GetString( "PathNotFound", resourceCulture );
            }
        }
    }
}
