//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace More
{
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute( "System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0" )]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessage
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute( "Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode" )]
        internal ExceptionMessage()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ( object.ReferenceEquals( resourceMan, null ) )
                {
#if NETFX_CORE
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager( "More.ExceptionMessage", typeof( ExceptionMessage ).GetTypeInfo().Assembly );
#else
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager( "More.ExceptionMessage", typeof( ExceptionMessage ).Assembly );
#endif
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute( global::System.ComponentModel.EditorBrowsableState.Advanced )]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The resource name &apos;{0}&apos; is ambiguous.  The assembly &apos;{1}&apos; contains {2} matching resources.  Specify a more qualified resource name to provide uniqueness..
        /// </summary>
        internal static string AmbiguousResourceException
        {
            get
            {
                return ResourceManager.GetString( "AmbiguousResourceException", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type name &apos;{0}&apos; is ambiguous..
        /// </summary>
        internal static string AmbiguousTypeName
        {
            get
            {
                return ResourceManager.GetString( "AmbiguousTypeName", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The application service &apos;{0}&apos; has not been added to the ApplicationLifetimeObjects collection..
        /// </summary>
        internal static string AppLifetimeObjectNotRegistered
        {
            get
            {
                return ResourceManager.GetString( "AppLifetimeObjectNotRegistered", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An assembly with the name &apos;{0}&apos; could not be found..
        /// </summary>
        internal static string AssemblyNotFound
        {
            get
            {
                return ResourceManager.GetString( "AssemblyNotFound", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Binding property must be set..
        /// </summary>
        internal static string AttachedSetterBindingUnset
        {
            get
            {
                return ResourceManager.GetString( "AttachedSetterBindingUnset", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attached setter cannot contain nested values..
        /// </summary>
        internal static string AttachedSetterCannotBeNested
        {
            get
            {
                return ResourceManager.GetString( "AttachedSetterCannotBeNested", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to bind the attached property Setter to {0}.{1}..
        /// </summary>
        internal static string AttachedSetterInvalidProperty
        {
            get
            {
                return ResourceManager.GetString( "AttachedSetterInvalidProperty", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The Property property must be set to a non-empty value..
        /// </summary>
        internal static string AttachedSetterPropertyUnset
        {
            get
            {
                return ResourceManager.GetString( "AttachedSetterPropertyUnset", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; property has not been set..
        /// </summary>
        internal static string AttributePropertyUnset
        {
            get
            {
                return ResourceManager.GetString( "AttributePropertyUnset", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to convert the string &apos;{0}&apos; to an enumeration of type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotConvertEnumValue
        {
            get
            {
                return ResourceManager.GetString( "CannotConvertEnumValue", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to create a the configuration section &apos;{0}&apos; using type &apos;{1}&apos;..
        /// </summary>
        internal static string CannotCreateConfigSection
        {
            get
            {
                return ResourceManager.GetString( "CannotCreateConfigSection", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A value of type {0} cannot be changed because it is incompatible with type {1} defined by property {2}..
        /// </summary>
        internal static string ChangeTypeMismatch
        {
            get
            {
                return ResourceManager.GetString( "ChangeTypeMismatch", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unable to download client configuration file from &apos;{0}&apos;..
        /// </summary>
        internal static string ConfigDownloadError
        {
            get
            {
                return ResourceManager.GetString( "ConfigDownloadError", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred parsing the configuration file..
        /// </summary>
        internal static string ConfigurationParseException
        {
            get
            {
                return ResourceManager.GetString( "ConfigurationParseException", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred parsing the value for attribute &apos;{0}&apos; on element &apos;{1}&apos;..
        /// </summary>
        internal static string ConfigurationValueParseException
        {
            get
            {
                return ResourceManager.GetString( "ConfigurationValueParseException", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The ConvertBack method is not supported by the converter..
        /// </summary>
        internal static string ConvertBackUnsupported
        {
            get
            {
                return ResourceManager.GetString( "ConvertBackUnsupported", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only a single enumeration is supported by this IEnumerable..
        /// </summary>
        internal static string DeserializeGetEnumerator
        {
            get
            {
                return ResourceManager.GetString( "DeserializeGetEnumerator", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The key &apos;{0}&apos; cannot be specified more than once..
        /// </summary>
        internal static string DuplicateAppSettingKey
        {
            get
            {
                return ResourceManager.GetString( "DuplicateAppSettingKey", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration section &apos;{0}&apos; cannot be defined more than once..
        /// </summary>
        internal static string DuplicateConfigSection
        {
            get
            {
                return ResourceManager.GetString( "DuplicateConfigSection", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The package does not contain any files..
        /// </summary>
        internal static string EmptyPackage
        {
            get
            {
                return ResourceManager.GetString( "EmptyPackage", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The entity set name for type {0} could not be resolved..
        /// </summary>
        internal static string EntitySetNameResolutionFailed
        {
            get
            {
                return ResourceManager.GetString( "EntitySetNameResolutionFailed", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid format. The format must be &apos;G&apos; or &apos;D&apos;..
        /// </summary>
        internal static string EnumConverterException
        {
            get
            {
                return ResourceManager.GetString( "EnumConverterException", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A converter parameter corresponding to a valid enumeration value must be specified in the current usage context..
        /// </summary>
        internal static string EnumConverterParameterExpected
        {
            get
            {
                return ResourceManager.GetString( "EnumConverterParameterExpected", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified converter parameter &apos;{1}&apos; is not a valid enumeration value for {0}..
        /// </summary>
        internal static string EnumConverterParameterInvalid
        {
            get
            {
                return ResourceManager.GetString( "EnumConverterParameterInvalid", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The event &quot;{0}&quot; on type &quot;{1}&quot; has an incompatible signature. Make sure the event is public and satisfies the EventHandler delegate..
        /// </summary>
        internal static string EventTriggerBaseInvalidEventExceptionMessage
        {
            get
            {
                return ResourceManager.GetString( "EventTriggerBaseInvalidEventExceptionMessage", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot find an event named &quot;{0}&quot; on type &quot;{1}&quot;..
        /// </summary>
        internal static string EventTriggerCannotFindEventNameExceptionMessage
        {
            get
            {
                return ResourceManager.GetString( "EventTriggerCannotFindEventNameExceptionMessage", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; must refer to a property declared by type {1}..
        /// </summary>
        internal static string ExpressionMustReferToPropertyOfDeclaredType
        {
            get
            {
                return ResourceManager.GetString( "ExpressionMustReferToPropertyOfDeclaredType", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The expression &apos;{0}&apos; must refer to a property..
        /// </summary>
        internal static string ExpresssionMustReferToProperty
        {
            get
            {
                return ResourceManager.GetString( "ExpresssionMustReferToProperty", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The task &apos;{0}&apos; with identifier &apos;{1}&apos; requires the service &apos;{2}&apos;, but that service failed to resolve from the supplied service provider..
        /// </summary>
        internal static string FailedToResolveServiceForTask
        {
            get
            {
                return ResourceManager.GetString( "FailedToResolveServiceForTask", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unspecified exception occurred..
        /// </summary>
        internal static string HostException
        {
            get
            {
                return ResourceManager.GetString( "HostException", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot convert type &apos;{0}&apos; to type &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidCast
        {
            get
            {
                return ResourceManager.GetString( "InvalidCast", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The catalog is trying to transition to an invalid state.  This occurs when you call DownloadAsync more than once or CancelAsync is called at an incorrect time..
        /// </summary>
        internal static string InvalidCatalogStateChange
        {
            get
            {
                return ResourceManager.GetString( "InvalidCatalogStateChange", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid visual state for the {0} control..
        /// </summary>
        internal static string InvalidControlVisualState
        {
            get
            {
                return ResourceManager.GetString( "InvalidControlVisualState", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The converter parameter must be of type &apos;{0}&apos; or a value that is convertible to type &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidConverterParameter
        {
            get
            {
                return ResourceManager.GetString( "InvalidConverterParameter", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The package is invalid..
        /// </summary>
        internal static string InvalidPackage
        {
            get
            {
                return ResourceManager.GetString( "InvalidPackage", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to SortDescription&apos;s property name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string InvalidPropertyName
        {
            get
            {
                return ResourceManager.GetString( "InvalidPropertyName", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; was not expected.  The root configuration element must be &apos;configuration&apos;..
        /// </summary>
        internal static string InvalidRootConfigElement
        {
            get
            {
                return ResourceManager.GetString( "InvalidRootConfigElement", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; is not a valid shell view because it does not implement the &apos;{1}&apos; interface..
        /// </summary>
        internal static string InvalidShellView
        {
            get
            {
                return ResourceManager.GetString( "InvalidShellView", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified object must be of type &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidTypeException
        {
            get
            {
                return ResourceManager.GetString( "InvalidTypeException", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; must be public, non-abstract, and implement the &apos;{1}&apos; interface..
        /// </summary>
        internal static string InvalidValueConverterType
        {
            get
            {
                return ResourceManager.GetString( "InvalidValueConverterType", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The attribute &apos;{0}&apos; must be specified..
        /// </summary>
        internal static string MissingConfigAttribute
        {
            get
            {
                return ResourceManager.GetString( "MissingConfigAttribute", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; does not have a corresponding configuration section..
        /// </summary>
        internal static string MissingConfigSection
        {
            get
            {
                return ResourceManager.GetString( "MissingConfigSection", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type {0} does not have a DependencyProperty named &apos;{0}&apos;..
        /// </summary>
        internal static string MissingDependencyProperty
        {
            get
            {
                return ResourceManager.GetString( "MissingDependencyProperty", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The task &apos;{0}&apos; of type &apos;{1}&apos; indicates that it depends on a task of type &apos;{2}&apos;, but a matching task could not be found..
        /// </summary>
        internal static string MissingDependentTask
        {
            get
            {
                return ResourceManager.GetString( "MissingDependentTask", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type {0} does not have a member &apos;{1}&apos;..
        /// </summary>
        internal static string MissingMemberException
        {
            get
            {
                return ResourceManager.GetString( "MissingMemberException", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The resource &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string MissingResourceException
        {
            get
            {
                return ResourceManager.GetString( "MissingResourceException", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The host was configured to execute a task of type &apos;{0}&apos;, but the task could not be resolved..
        /// </summary>
        internal static string MissingStartupTask
        {
            get
            {
                return ResourceManager.GetString( "MissingStartupTask", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple matches for task &apos;{0}&apos; were found.  Each task must have exactly one export..
        /// </summary>
        internal static string MultipleStartupTasksExported
        {
            get
            {
                return ResourceManager.GetString( "MultipleStartupTasksExported", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The package contains multiple files, but only one file was expected..
        /// </summary>
        internal static string MutipleFilePackage
        {
            get
            {
                return ResourceManager.GetString( "MutipleFilePackage", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The host was unable to find a shell view that matches the type &apos;{0}&apos;..
        /// </summary>
        internal static string NoCandidateShellView
        {
            get
            {
                return ResourceManager.GetString( "NoCandidateShellView", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A ConvertBack rule could not be found for the value &apos;{0}&apos;..
        /// </summary>
        internal static string NoConvertBackRule
        {
            get
            {
                return ResourceManager.GetString( "NoConvertBackRule", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The UseNumericFormat property must be set to true in order to convert to type {0}..
        /// </summary>
        internal static string NumericFormatMustBeUsedToConvertEnumToNumber
        {
            get
            {
                return ResourceManager.GetString( "NumericFormatMustBeUsedToConvertEnumToNumber", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The collection is read-only..
        /// </summary>
        internal static string ReadOnlyCollection
        {
            get
            {
                return ResourceManager.GetString( "ReadOnlyCollection", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An object of type &quot;{0}&quot; cannot have a {3} property of type &quot;{1}&quot;. Instances of type &quot;{0}&quot; can have only a {3} property of type &quot;{2}&quot;..
        /// </summary>
        internal static string RetargetedTypeConstraintViolatedExceptionMessage
        {
            get
            {
                return ResourceManager.GetString( "RetargetedTypeConstraintViolatedExceptionMessage", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred loading the shell view.  See the inner exception for details..
        /// </summary>
        internal static string ShellViewLoadException
        {
            get
            {
                return ResourceManager.GetString( "ShellViewLoadException", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The host was unable to create a shell view of type &apos;{0}&apos;..
        /// </summary>
        internal static string ShellViewResolutionFailed
        {
            get
            {
                return ResourceManager.GetString( "ShellViewResolutionFailed", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The service has not been started. The StartService method must be called before the application service context is available..
        /// </summary>
        internal static string StartServiceHasNotBeenCalled
        {
            get
            {
                return ResourceManager.GetString( "StartServiceHasNotBeenCalled", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The task &apos;{0}&apos; has already been registered and cannot be registered more than once..
        /// </summary>
        internal static string TaskCannotBeRegisteredMoreThanOnce
        {
            get
            {
                return ResourceManager.GetString( "TaskCannotBeRegisteredMoreThanOnce", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; configuration section cannot be defined multiple times..
        /// </summary>
        internal static string TooManyConfigSections
        {
            get
            {
                return ResourceManager.GetString( "TooManyConfigSections", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The specified item must be assignable from type &apos;{0}&apos;..
        /// </summary>
        internal static string UnassignableType
        {
            get
            {
                return ResourceManager.GetString( "UnassignableType", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An unexpected exception occurred while deserializing the configuration section &apos;{0}&apos;.  See the inner exception for more information..
        /// </summary>
        internal static string UnexpectedConfigSectionParseError
        {
            get
            {
                return ResourceManager.GetString( "UnexpectedConfigSectionParseError", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration attribute &apos;{0}&apos; on element &apos;{1}&apos; is not supported..
        /// </summary>
        internal static string UnknownConfigAttribute
        {
            get
            {
                return ResourceManager.GetString( "UnknownConfigAttribute", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The configuration element &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string UnknownConfigElement
        {
            get
            {
                return ResourceManager.GetString( "UnknownConfigElement", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The target conversion type &apos;{0}&apos; is not supported by the converter..
        /// </summary>
        internal static string UnsupportedConversionType
        {
            get
            {
                return ResourceManager.GetString( "UnsupportedConversionType", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Values of type &apos;{0}&apos; are not supported by the converter..
        /// </summary>
        internal static string UnsupportedValueType
        {
            get
            {
                return ResourceManager.GetString( "UnsupportedValueType", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The element &apos;{0}&apos; was supplied, but the element &apos;{1}&apos; was expected..
        /// </summary>
        internal static string WrongConfigurationElement
        {
            get
            {
                return ResourceManager.GetString( "WrongConfigurationElement", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to IAsyncResult object did not come from the corresponding async method on this type..
        /// </summary>
        internal static string WrongIAsyncResult
        {
            get
            {
                return ResourceManager.GetString( "WrongIAsyncResult", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An instance of a Behavior cannot be attached to more than one object at a time..
        /// </summary>
        internal static string CannotHostBehaviorMultipleTimesExceptionMessage
        {
            get
            {
                return ResourceManager.GetString( "CannotHostBehaviorMultipleTimesExceptionMessage", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot attach type "{0}" to type "{1}". Instances of type "{0}" can only be attached to objects of type "{2}"..
        /// </summary>
        internal static string TypeConstraintViolatedExceptionMessage
        {
            get
            {
                return ResourceManager.GetString( "TypeConstraintViolatedExceptionMessage", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Wrong thread..
        /// </summary>
        internal static string WrongThread
        {
            get
            {
                return ResourceManager.GetString( "WrongThread", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An operation cannot be continued with a static method..
        /// </summary>
        internal static string ContinuationCannotBeStaticMethod
        {
            get
            {
                return ResourceManager.GetString( "ContinuationCannotBeStaticMethod", resourceCulture );
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The type '{0}' does not have a parameterless constructor..
        /// </summary>
        internal static string NoParameterlessConstructor
        {
            get
            {
                return ResourceManager.GetString( "NoParameterlessConstructor", resourceCulture );
            }
        }
    }
}
