//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace More.VisualStudio {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("More.VisualStudio.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data Connection.
        /// </summary>
        internal static string AddDataConnectionTitle {
            get {
                return ResourceManager.GetString("AddDataConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding item &apos;{0}&apos;..
        /// </summary>
        internal static string AddTemplateItem {
            get {
                return ResourceManager.GetString("AddTemplateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding item &apos;{0}&apos; to &apos;{1}&apos;..
        /// </summary>
        internal static string AddTemplateSubItem {
            get {
                return ResourceManager.GetString("AddTemplateSubItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Activation.
        /// </summary>
        internal static string AppSearchOption {
            get {
                return ResourceManager.GetString("AppSearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Activation.
        /// </summary>
        internal static string AppShareOption {
            get {
                return ResourceManager.GetString("AppShareOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackCaption {
            get {
                return ResourceManager.GetString("BackCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelCaption {
            get {
                return ResourceManager.GetString("CancelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A connection string with the name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ConnectionStringNameNonUnique {
            get {
                return ResourceManager.GetString("ConnectionStringNameNonUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name must be specified for the new connection string..
        /// </summary>
        internal static string ConnectionStringNameUnspecified {
            get {
                return ResourceManager.GetString("ConnectionStringNameUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (Settings).
        /// </summary>
        internal static string DataConnectionDisplayName {
            get {
                return ResourceManager.GetString("DataConnectionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbContext Template Wizard.
        /// </summary>
        internal static string DbContextItemTemplateWizardTitle {
            get {
                return ResourceManager.GetString("DbContextItemTemplateWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save connection string settings in *.config as:.
        /// </summary>
        internal static string DefaultSaveToConfigurationCaption {
            get {
                return ResourceManager.GetString("DefaultSaveToConfigurationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Type.
        /// </summary>
        internal static string DefaultTypeSelectionTitle {
            get {
                return ResourceManager.GetString("DefaultTypeSelectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model provides property change notification, validation support, and implements IEditableObject with editing transaction support..
        /// </summary>
        internal static string EditableObjectDesc {
            get {
                return ResourceManager.GetString("EditableObjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Framework 6.
        /// </summary>
        internal static string EF6 {
            get {
                return ResourceManager.GetString("EF6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Framework 7.
        /// </summary>
        internal static string EF7 {
            get {
                return ResourceManager.GetString("EF7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluating required packages....
        /// </summary>
        internal static string EvaluatingPackages {
            get {
                return ResourceManager.GetString("EvaluatingPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Existing Model.
        /// </summary>
        internal static string ExistingModelTitle {
            get {
                return ResourceManager.GetString("ExistingModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an Existing View Model.
        /// </summary>
        internal static string ExistingViewModelTitle {
            get {
                return ResourceManager.GetString("ExistingViewModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An existing view model must be selected..
        /// </summary>
        internal static string ExistingViewModelUnspecified {
            get {
                return ResourceManager.GetString("ExistingViewModelUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string FinishCaption {
            get {
                return ResourceManager.GetString("FinishCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement IDialogView&lt;T&gt;.
        /// </summary>
        internal static string ImplementIDialogViewT {
            get {
                return ResourceManager.GetString("ImplementIDialogViewT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports dialog semantics and allows its view model to be attached at runtime..
        /// </summary>
        internal static string ImplementIDialogViewTDesc {
            get {
                return ResourceManager.GetString("ImplementIDialogViewTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement IReadOnlyRepository&lt;T&gt;.
        /// </summary>
        internal static string ImplementIReadOnlyRepositoryT {
            get {
                return ResourceManager.GetString("ImplementIReadOnlyRepositoryT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DbContext supports read-only query semantics..
        /// </summary>
        internal static string ImplementIReadOnlyRepositoryTDesc {
            get {
                return ResourceManager.GetString("ImplementIReadOnlyRepositoryTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement IRepository&lt;T&gt;.
        /// </summary>
        internal static string ImplementIRepositoryT {
            get {
                return ResourceManager.GetString("ImplementIRepositoryT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DbContext supports read-write query semantics..
        /// </summary>
        internal static string ImplementIRepositoryTDesc {
            get {
                return ResourceManager.GetString("ImplementIRepositoryTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement IUnitOfWork&lt;T&gt;.
        /// </summary>
        internal static string ImplementIUnitOfWorkT {
            get {
                return ResourceManager.GetString("ImplementIUnitOfWorkT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The DbContext supports write-only semantics..
        /// </summary>
        internal static string ImplementIUnitOfWorkTDesc {
            get {
                return ResourceManager.GetString("ImplementIUnitOfWorkTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement IView&lt;T&gt;.
        /// </summary>
        internal static string ImplementIViewT {
            get {
                return ResourceManager.GetString("ImplementIViewT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view exposes a view model..
        /// </summary>
        internal static string ImplementIViewTDesc {
            get {
                return ResourceManager.GetString("ImplementIViewTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implement IView&lt;T, T&gt;.
        /// </summary>
        internal static string ImplementIViewTT {
            get {
                return ResourceManager.GetString("ImplementIViewTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view allows its view model to be attached at runtime..
        /// </summary>
        internal static string ImplementIViewTTDesc {
            get {
                return ResourceManager.GetString("ImplementIViewTTDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model provides property change notification and provides a basic implementation for user interaction. This option is typically used when your view model is supplied to an interaction which shows another view such as a window..
        /// </summary>
        internal static string InteractionDesc {
            get {
                return ResourceManager.GetString("InteractionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An object of type &apos;{0}&apos; must be specified for validation..
        /// </summary>
        internal static string InvalidObjectForValidation {
            get {
                return ResourceManager.GetString("InvalidObjectForValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Template Wizard.
        /// </summary>
        internal static string ItemTemplateWizardTitle {
            get {
                return ResourceManager.GetString("ItemTemplateWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Connection....
        /// </summary>
        internal static string NewConnectionCaption {
            get {
                return ResourceManager.GetString("NewConnectionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextCaption {
            get {
                return ResourceManager.GetString("NextCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active project was found in the solution..
        /// </summary>
        internal static string NoActiveProject {
            get {
                return ResourceManager.GetString("NoActiveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model implements the basic functionality of INotifyPropertyChanged..
        /// </summary>
        internal static string ObservableObjectDesc {
            get {
                return ResourceManager.GetString("ObservableObjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OKCaption {
            get {
                return ResourceManager.GetString("OKCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one item must be enabled..
        /// </summary>
        internal static string OneItemRequired {
            get {
                return ResourceManager.GetString("OneItemRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Files.
        /// </summary>
        internal static string OpenFileOption {
            get {
                return ResourceManager.GetString("OpenFileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding {0}.{1} to project....
        /// </summary>
        internal static string PackageInstallStatus {
            get {
                return ResourceManager.GetString("PackageInstallStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Only.
        /// </summary>
        internal static string PageOnly {
            get {
                return ResourceManager.GetString("PageOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view is a Page, which implements no additional interfaces..
        /// </summary>
        internal static string PageOnlyDesc {
            get {
                return ResourceManager.GetString("PageOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Template Wizard.
        /// </summary>
        internal static string ProjectTemplateWizardTitle {
            get {
                return ResourceManager.GetString("ProjectTemplateWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Files.
        /// </summary>
        internal static string SaveFileOption {
            get {
                return ResourceManager.GetString("SaveFileOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save connection string settings in {0} as:.
        /// </summary>
        internal static string SaveToConfigurationCaption {
            get {
                return ResourceManager.GetString("SaveToConfigurationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchOption {
            get {
                return ResourceManager.GetString("SearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Contacts.
        /// </summary>
        internal static string SelectContactOption {
            get {
                return ResourceManager.GetString("SelectContactOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Folders.
        /// </summary>
        internal static string SelectFolderOption {
            get {
                return ResourceManager.GetString("SelectFolderOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SettingsFlyout Only.
        /// </summary>
        internal static string SettingsFlyoutOnly {
            get {
                return ResourceManager.GetString("SettingsFlyoutOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view is a SettingsFlyout, which implements no additional interfaces..
        /// </summary>
        internal static string SettingsFlyoutOnlyDesc {
            get {
                return ResourceManager.GetString("SettingsFlyoutOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsOption {
            get {
                return ResourceManager.GetString("SettingsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string ShareOption {
            get {
                return ResourceManager.GetString("ShareOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string StatusInitializing {
            get {
                return ResourceManager.GetString("StatusInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing data sources....
        /// </summary>
        internal static string StatusInitializingDataSources {
            get {
                return ResourceManager.GetString("StatusInitializingDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Box.
        /// </summary>
        internal static string TextInputOption {
            get {
                return ResourceManager.GetString("TextInputOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Control Only.
        /// </summary>
        internal static string UserControlOnly {
            get {
                return ResourceManager.GetString("UserControlOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view is a UserControl, which implements no additional interfaces..
        /// </summary>
        internal static string UserControlOnlyDesc {
            get {
                return ResourceManager.GetString("UserControlOnlyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model provides property change notification and supports validation using data annotations when properties change..
        /// </summary>
        internal static string ValidatableObjectDesc {
            get {
                return ResourceManager.GetString("ValidatableObjectDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view support activation via the search contract..
        /// </summary>
        internal static string ViewAppSearchOptionDesc {
            get {
                return ResourceManager.GetString("ViewAppSearchOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports activation via the share contract..
        /// </summary>
        internal static string ViewAppShareOptionDesc {
            get {
                return ResourceManager.GetString("ViewAppShareOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Item Template Wizard.
        /// </summary>
        internal static string ViewItemTemplateWizardTitle {
            get {
                return ResourceManager.GetString("ViewItemTemplateWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model support activation via the search contract..
        /// </summary>
        internal static string ViewModelAppSearchOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelAppSearchOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model supports activation via the share contract..
        /// </summary>
        internal static string ViewModelAppShareOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelAppShareOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Model Item Template Wizard.
        /// </summary>
        internal static string ViewModelItemTemplateWizardTitle {
            get {
                return ResourceManager.GetString("ViewModelItemTemplateWizardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A view model with the name &apos;{0}&apos; already exists..
        /// </summary>
        internal static string ViewModelNameNonUnique {
            get {
                return ResourceManager.GetString("ViewModelNameNonUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name must be specified for the new view model..
        /// </summary>
        internal static string ViewModelNameUnspecified {
            get {
                return ResourceManager.GetString("ViewModelNameUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model supports file open user interactions..
        /// </summary>
        internal static string ViewModelOpenFileOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelOpenFileOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model supports file save user interactions..
        /// </summary>
        internal static string ViewModelSaveFileOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelSaveFileOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model supports the search contract..
        /// </summary>
        internal static string ViewModelSearchOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelSearchOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model supports contact selection user interactions..
        /// </summary>
        internal static string ViewModelSelectContactOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelSelectContactOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model supports folder selection user interactions..
        /// </summary>
        internal static string ViewModelSelectFolderOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelSelectFolderOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model supports the settings contract..
        /// </summary>
        internal static string ViewModelSettingsOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelSettingsOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model supports the share contract..
        /// </summary>
        internal static string ViewModelShareOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelShareOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view model supports simple text input user interactions..
        /// </summary>
        internal static string ViewModelTextInputOptionDesc {
            get {
                return ResourceManager.GetString("ViewModelTextInputOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports file open user interactions..
        /// </summary>
        internal static string ViewOpenFileOptionDesc {
            get {
                return ResourceManager.GetString("ViewOpenFileOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports file save user interactions..
        /// </summary>
        internal static string ViewSaveFileOptionDesc {
            get {
                return ResourceManager.GetString("ViewSaveFileOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports the search contract..
        /// </summary>
        internal static string ViewSearchOptionDesc {
            get {
                return ResourceManager.GetString("ViewSearchOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports contact selection user interactions..
        /// </summary>
        internal static string ViewSelectContactOptionDesc {
            get {
                return ResourceManager.GetString("ViewSelectContactOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports folder selection user interactions..
        /// </summary>
        internal static string ViewSelectFolderOptionDesc {
            get {
                return ResourceManager.GetString("ViewSelectFolderOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports the settings contract..
        /// </summary>
        internal static string ViewSettingsOptionDesc {
            get {
                return ResourceManager.GetString("ViewSettingsOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports the share contract..
        /// </summary>
        internal static string ViewShareOptionDesc {
            get {
                return ResourceManager.GetString("ViewShareOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view supports simple text input user interactions..
        /// </summary>
        internal static string ViewTextInputOptionDesc {
            get {
                return ResourceManager.GetString("ViewTextInputOptionDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Only.
        /// </summary>
        internal static string WindowOnly {
            get {
                return ResourceManager.GetString("WindowOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view is a Window, which implements no additional interfaces..
        /// </summary>
        internal static string WindowOnlyDesc {
            get {
                return ResourceManager.GetString("WindowOnlyDesc", resourceCulture);
            }
        }
    }
}
